// FETCH MOVIES
export const FETCH_MOVIES_LOADING = "FETCH_MOVIES_LOADING"
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS"
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE"

// SINGLE MOVIES

export const FETCH_SINGLE_MOVIES_LOADING = "FETCH_SINGLE_MOVIES_LOADING"
export const FETCH_SINGLE_MOVIES_SUCCESS = "FETCH_SINGLE_MOVIES_SUCCESS"
export const FETCH_SINGLE_MOVIES_FAILURE = "FETCH_SINGLE_MOVIES_FAILURE"

// SEARCH MOVIES
export const SEARCH_MOVIES_LOADING = "SEARCH_MOVIES_LOADING"
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS"
export const SEARCH_MOVIES_FAILURE = "SEARCH_MOVIES_FAILURE"

export const SEARCH_QUERY = "SEARCH_QUERY"

export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER'
export const SET_TOTAL_PAGE_NUMBER = 'SET_TOTAL_PAGE_NUMBER'